#nelmio_cors:
#    defaults:
#        origin_regex: true
#        allow_origin: ['http://localhost:8081']
#        allow_credentials: true
#        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#        allow_headers: ['Content-Type', 'Authorization']
#        expose_headers: ['Link']
#        max_age: 3600
#
#    paths:
#        '^/api/':
#            allow_origin: ['http://localhost:8081']
#            allow_credentials: true
#            allow_headers: ['*']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#        '^/': null


nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://52.207.103.78:8081', 'http://localhost:8081']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Content-Disposition', 'Link']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin: ['http://52.207.103.78:8081', 'http://localhost:8081']
            allow_headers: ['Content-Type', 'Authorization', 'Accept']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
            allow_credentials: true
        '^/': null